// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Airport")]
	public class Airport
	{
		[Column("id"       , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long    Id        { get; set; } // integer
		[Column("latitude"                                                                                    )] public double? Latitude  { get; set; } // real
		[Column("longitude"                                                                                   )] public double? Longitude { get; set; } // real
		[Column("name"     , CanBeNull    = false                                                             )] public string  Name      { get; set; } = null!; // text(max)
		[Column("iata"                                                                                        )] public string? Iata      { get; set; } // text(max)

		#region Associations
		/// <summary>
		/// FK_Route_0_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Route.Airport2))]
		public IEnumerable<Route> Routes { get; set; } = null!;

		/// <summary>
		/// FK_Route_2_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Route.Airport1))]
		public IEnumerable<Route> Routes1 { get; set; } = null!;
		#endregion
	}
}
