// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("alliance")]
	public class Alliance
	{
		[Column("id"  , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long   Id   { get; set; } // integer
		[Column("name", CanBeNull    = false                                                             )] public string Name { get; set; } = null!; // text(max)

		#region Associations
		/// <summary>
		/// FK_Airline_0_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Airline.Alliance))]
		public IEnumerable<Airline> Airlines { get; set; } = null!;
		#endregion
	}
}
