// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Route")]
	public class Route
	{
		[Column("id"      , IsPrimaryKey = true)] public long  Id       { get; set; } // integer
		[Column("airline"                      )] public long? Airline  { get; set; } // integer
		[Column("airport1"                     )] public long? Airport1 { get; set; } // integer
		[Column("airport2"                     )] public long? Airport2 { get; set; } // integer

		#region Associations
		/// <summary>
		/// FK_Route_0_0
		/// </summary>
		[Association(ThisKey = nameof(Airport2), OtherKey = nameof(Airport.Id))]
		public Airport? FkRoute00 { get; set; }

		/// <summary>
		/// FK_Route_1_0
		/// </summary>
		[Association(ThisKey = nameof(Airline), OtherKey = nameof(DataModel.Airline.Id))]
		public Airline? FkRoute10 { get; set; }

		/// <summary>
		/// FK_Route_2_0
		/// </summary>
		[Association(ThisKey = nameof(Airport1), OtherKey = nameof(Airport.Id))]
		public Airport? FkRoute20 { get; set; }
		#endregion
	}
}
