// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("kategorie")]
	public class Kategorie
	{
		[Column("KatID", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long    KatId { get; set; } // integer
		[Column("Name"                                                                                   )] public string? Name  { get; set; } // text(max)

		#region Associations
		/// <summary>
		/// FK_restaurants_0_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(KatId), OtherKey = nameof(Restaurant.Kategorie))]
		public IEnumerable<Restaurant> Restaurants { get; set; } = null!;
		#endregion
	}
}
