// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("restaurants")]
	public class Restaurant
	{
		[Column("RestID"     , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long     RestId      { get; set; } // integer
		[Column("Name"                                                                                         )] public string?  Name        { get; set; } // text(max)
		[Column("Longitude"                                                                                    )] public decimal? Longitude   { get; set; } // numeric
		[Column("Latitude"                                                                                     )] public decimal? Latitude    { get; set; } // numeric
		[Column("Review"                                                                                       )] public long?    Review      { get; set; } // integer
		[Column("Description"                                                                                  )] public string?  Description { get; set; } // text(max)
		[Column("KatNr"                                                                                        )] public long?    KatNr       { get; set; } // integer

		#region Associations
		/// <summary>
		/// FK_restaurants_0_0
		/// </summary>
		[Association(ThisKey = nameof(KatNr), OtherKey = nameof(Kategorie.KatId))]
		public Kategorie? FkRestaurants00 { get; set; }
		#endregion
	}
}
