// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class RoutingDb : DataConnection
	{
		public RoutingDb()
		{
			InitDataContext();
		}

		public RoutingDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

        public RoutingDb(string version, string configuration)
            : base(version, configuration)
        {
            InitDataContext();
        }

        public RoutingDb(DataOptions<RoutingDb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<Connection> Connections => this.GetTable<Connection>();
		public ITable<Router>     Routers     => this.GetTable<Router>();
	}

	public static partial class ExtensionMethods
	{
		#region Table Extensions
		public static Connection? Find(this ITable<Connection> table, long id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<Connection?> FindAsync(this ITable<Connection> table, long id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}

		public static Router? Find(this ITable<Router> table, long id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<Router?> FindAsync(this ITable<Router> table, long id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}
		#endregion
	}
}
